import type { Metadata } from 'next'
import { Geist_Mono, Orbitron, Inter, Manrope } from 'next/font/google'
import './globals.css'
import DemoModalProvider from '@/components/shadcn-studio/blocks/demo-modal-provider'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const orbitron = Orbitron({
  variable: '--font-orbitron',
  subsets: ['latin'],
  weight: ['900'],
})

export const metadata: Metadata = {
  title: 'Shadcn Studio Export',
  description: 'Generated by Shadcn Studio',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={`${inter.variable} ${manrope.variable} ${geistMono.variable} ${orbitron.variable} antialiased`}>
      <body>
        {children}
        <DemoModalProvider />
      </body>
    </html>
  )
}

